# Book settings
title: OpenTurbine - Flexible Multibody Structural Dynamics Code for Wind Turbines
author: National Renewable Energy Laboratory (NREL) and Sandia National Laboratories (SNL)
copyright: 2023 - Present, MIT License
only_build_toc_files: false # build all files

# Execution settings
execute:
  execute_notebooks: auto # force re-execution of notebooks on each build

# HTML-specific settings
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

# Github repository info
repository:
  url: https://github.com/exawind/openturbine
  path_to_book: docs
  branch: main

# Configure Sphinx
sphinx:
  mermaid_version: 8.13.3
  extra_extensions:
    - 'sphinxcontrib.mermaid' # for diagrams
    - 'sphinx.ext.mathjax'    # for math
