# Book settings
title: OpenTurbine
author: National Renewable Energy Laboratory (NREL)
copyright: '2023 - Present'
only_build_toc_files: true

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: auto

# Information about where the book exists on the web
repository:
  url: https://github.com/exawind/openturbine
  path_to_book: docs
  branch: main

# Add GitHub buttons
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

# Configure Sphinx
sphinx:
  mermaid_version: 8.13.3
  extra_extensions:
    - 'sphinxcontrib.mermaid'
    - 'sphinx.ext.mathjax'
