# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: OpenTurbine
author: National Renewable Energy Laboratory
# logo: logo.png
copyright: '2023'
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/exawind/openturbine
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  # google_analytics_id: G-L8RGXZCW3F

sphinx:
  mermaid_version: 8.13.3
  extra_extensions:
    - 'sphinxcontrib.mermaid'
#   - 'sphinx.ext.autodoc'
#   - 'sphinx.ext.autosummary'
#   - 'sphinx.ext.viewcode'
#   config:
#     html_theme: sphinx_book_theme
