name: OpenTurbine-CI

on: push

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - name: Check formatting
      uses: DoozyX/clang-format-lint-action@v0.15
      with:
        source: './src ./tests/unit_tests'
        exclude: '.'
        extensions: 'H,h,cpp'
        clangFormatVersion: 14
  CPU:
    needs: Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Install LAPACK
      run: |
        sudo apt-get install liblapack-dev
        sudo apt-get install liblapacke-dev
    - name: Install Kokkos
      run: |
        git clone https://github.com/kokkos/kokkos
        cd kokkos
        mkdir build
        cd build
        cmake ../
        make
        sudo make install
    - name: Install Kokkos-Kernels
      run: |
        git clone https://github.com/kokkos/kokkos-kernels
        cd kokkos-kernels
        mkdir build
        cd build
        cmake ../ -D KokkosKernels_ENABLE_TPL_BLAS="ON"
        make
        sudo make install
    - name: Install GoogleTest
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
        sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: Clone
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Test
      run: |
        mkdir build
        cd build
        cmake .. -DOTURB_ENABLE_TESTS:BOOL=ON -DKokkosKernels_DIR=$kokkos_kernels_dir
        make
        ./openturbine -h
        ./openturbine_unit_tests
