name: OpenTurbine CI

on: push
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:

  CPU:
    # needs: Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Install Spack
      run: |
        git clone https://github.com/spack/spack ~/.spack/Spack
        . ~/.spack/Spack/share/spack/setup-env.sh
    - name: Clone
      uses: actions/checkout@v3
      with: 
        submodules: true
    - name: Test
      run: |
        . ~/.spack/Spack/share/spack/setup-env.sh
        spack --version
        spack info kokkos
        spack install kokkos
    # - name: Dependencies
    #   run: ${{matrix.install_deps}}
    # - name: Setup
    #   run: |
    #     echo "NUM_PROCS=${{matrix.procs}}" >> $GITHUB_ENV
    # - name: Configure
    #   run: |
    #     cmake -G Ninja \
    #       -B ${{runner.workspace}}/build-ci-${{matrix.build_type}} \
    #       -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/install-${{matrix.build_type}} \
    #       -DCMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} \
    #       ${{github.workspace}}
    # - name: Build
    #   working-directory: ${{runner.workspace}}/build-ci-${{matrix.build_type}}
    #   run: |
    #     echo "::add-matcher::.github/problem-matchers/gcc.json"
    #     cmake --build . -- -j ${{env.NUM_PROCS}} 2>&1 | tee -a build-output.txt
    # - name: Test
    #   working-directory: ${{runner.workspace}}/build-ci-${{matrix.build_type}}
    #   run: |
    #     ctest ${{matrix.ctest_args}} --output-on-failure


