#name: OpenTurbine-CI
#
#on: push
#
#jobs:
#  ClangTidy:
#    runs-on: ubuntu-latest
#    env:
#      CMAKE_BUILD_PARALLEL_LEVEL: 4
#    strategy:
#      fail-fast: false
#    steps:
#    - name: Cache install Trilinos
#      id: cache-trilinos
#      uses: actions/cache@v3
#      with:
#        path: ${{ github.workspace }}/spack
#        key: linux-spack
#    - name: Install Trilinos
#      if: steps.cache-trilinos.outputs.cache-hit != 'true'
#      run: |
#        git clone https://github.com/spack/spack.git
#        source spack/share/spack/setup-env.sh
#        spack compiler find
#        spack external find
#        spack install googletest
#        spack install trilinos@master~mpi~epetra+basker
#    - name: Cache install yaml-cpp
#      id: cache-yaml-cpp
#      uses: actions/cache@v3
#      with:
#        path: ${{ github.workspace }}/spack
#        key: linux-yaml-cpp
#    - name: Install yaml-cpp
#      if: steps.cache-yaml-cpp.outputs.cache-hit != 'true'
#      run: |
#        source spack/share/spack/setup-env.sh
#        spack install yaml-cpp
#    - name: Clone
#      uses: actions/checkout@v4
#      with:
#        submodules: true
#        path: openturbine
#    - name: Run Clang-Tidy
#      run: |
#        source spack/share/spack/setup-env.sh
#        spack load trilinos
#        spack load googletest
#        spack load yaml-cpp
#        cd openturbine
#        mkdir build-clangtidy
#        cd build-clangtidy
#        cmake .. \
#          -DOpenTurbine_ENABLE_CLANG_TIDY=ON \
#          -DCMAKE_BUILD_TYPE=Debug
#        cmake --build .
