name: OpenTurbine-CI

#on: push
on:
  push:
    branches: [main]

jobs:
  Correctness-Linux:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 2
      CXX: ${{matrix.compiler}}
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++, clang++]
        build_type: [Release, Debug]
        build_external: [all, none]
    steps:
    - name: Cache install Dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/spack
        key: linux-spack
    - name: Install Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/spack/spack.git
        source spack/share/spack/setup-env.sh
        spack compiler find
        spack install googletest
        spack install cppcheck
        spack install yaml-cpp
        spack install trilinos@master~epetra ^kokkos-kernels+blas+lapack
    - name: Clone
      uses: actions/checkout@v4
      with:
        submodules: true
        path: openturbine
    - name: Test OpenTurbine
      run: |
        source spack/share/spack/setup-env.sh
        spack load trilinos
        spack load googletest
        spack load cppcheck
        spack load yaml-cpp
        cd openturbine
        mkdir build
        cd build
        cmake .. \
          -DOpenTurbine_ENABLE_SANITIZER_ADDRESS=${{ matrix.build_external == 'none' }} \
          -DOpenTurbine_ENABLE_SANITIZER_LEAK=${{ matrix.build_external == 'none' }} \
          -DOpenTurbine_ENABLE_SANITIZER_UNDEFINED=${{ matrix.build_external == 'none' }} \
          -DOpenTurbine_ENABLE_CPPCHECK=ON \
          -DOpenTurbine_ENABLE_CLANG_TIDY=ON \
          -DOpenTurbine_WARNINGS_AS_ERRORS=ON \
          -DOpenTurbine_BUILD_OPENFAST_ADI=${{ matrix.build_external == 'all' }} \
          -DOpenTurbine_BUILD_ROSCO_CONTROLLER=${{ matrix.build_external == 'all' }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build .
        ctest --output-on-failure
