name: OpenTurbine-CI

on: push

jobs:
  Correctness-Linux:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 2
      CXX: ${{matrix.compiler}}
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++, clang++]
        build_type: [Release, Debug]
    steps:
    - name: Cache install Trilinos
      id: cache-trilinos
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/spack
        key: linux-spack
    - name: Install Trilinos
      if: steps.cache-trilinos.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/spack/spack.git
        source spack/share/spack/setup-env.sh
        spack compiler find
        spack external find
        spack install googletest
        spack install trilinos@master~mpi~epetra+basker
    - name: Install yaml-cpp
      run:
        source spack/share/spack/setup-env.sh
        spack install yaml-cpp
    - name: Clone
      uses: actions/checkout@v4
      with:
        submodules: true
        path: openturbine
    - name: Test OpenTurbine
      run: |
        source spack/share/spack/setup-env.sh
        spack load trilinos
        spack load googletest
        spack load yaml-cpp
        cd openturbine
        mkdir build
        cd build
        cmake .. \
          -DOpenTurbine_ENABLE_SANITIZER_ADDRESS=ON \
          -DOpenTurbine_ENABLE_SANITIZER_LEAK=ON \
          -DOpenTurbine_ENABLE_SANITIZER_UNDEFINED=ON \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build .
        cp src/*.dll tests/unit_tests/
        ctest --output-on-failure
