name: Deploy OpenTurbine Documentation

on:
  push:
    paths:
    - docs/**
    - .github/workflows/deploy_docs.yaml

jobs:
  Deploy-Docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends graphviz libenchant-2-dev
        python3 -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: Install Doxygen
      uses: ssciwr/doxygen-install@v1.6.0
      with:
        version: "1.12.0"
    - name: Build Documentation
      run: |
        mkdir -p build-docs
        cd build-docs
        cmake .. -DOpenTurbine_ENABLE_DOCUMENTATION=ON
        cmake --build .
    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
