name: OpenTurbine-CI

on: push

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run clang-format
      run: |
        find . -regex '.*\.\(cpp\|hpp\|c\|h\)' -exec clang-format -i {} \;
        
    - name: Check for formatting changes
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "Code is not formatted. Please run clang-format."
          git diff
          exit 1
        else
          echo "Code is properly formatted."
        fi

