name: OpenTurbine-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run clang-format
      run: |
        clang-format --version
        find . -regex '.*\.\(cpp\|hpp\|c\|h\)' -exec clang-format-18 -i {} \;
    - name: Check for formatting changes
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "Code is not formatted. Please run clang-format."
          git diff
          exit 1
        else
          echo "Code is properly formatted."
        fi
