name: OpenTurbine-Install

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/deploy_docs.yaml'

jobs:
  Correctness-Linux:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 2
      CXX: g++
    steps:
    - name: Install OpenTurbine
      run: |
        git clone https://github.com/spack/spack.git
        source spack/share/spack/setup-env.sh
        spack compiler find
        spack env create -d .
        spack env activate .
        spack add openturbine
        spack install
        spack develop openturbine@main
        spack concretize -f
        cd openturbine
        git checkout ${{ BRANCH_NAME }}
        spack install
        cd openturbine/tests/documentation_tests/floating_platform
        mkdir build
        cd build
        spack build-env openturbine -- bash
        cmake ../
        make -j 2
        ./floating_platform
