name: OpenTurbine-Install

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/deploy_docs.yaml'

jobs:
  Correctness-Linux:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 2
      CXX: g++
      CC: gcc
    steps:
    - name: Install OpenTurbine
      run: |
        git clone https://github.com/spack/spack.git
        source spack/share/spack/setup-env.sh
        spack compiler find
        spack env create -d .
        spack env activate .
        spack add openturbine ^netcdf-c~mpi ^hdf5~mpi ^cmake~ncurses
        spack develop openturbine@main
        spack concretize -f
        cd openturbine
        git checkout ${{ github.head_ref || github.ref_name}}
        spack install
    - name: Floating Platform Test
      run: |
        source spack/share/spack/setup-env.sh
        spack env activate .
        cd openturbine/tests/documentation_tests/floating_platform
        mkdir build
        cd build
        spack build-env openturbine -- bash
        cmake ../
        make -j 2
        ./floating_platform
    - name: Turbine Test
      run: |
        source spack/share/spack/setup-env.sh
        spack env activate .
        cd openturbine/tests/documentation_tests/iea15mw_turbine
        mkdir build
        cd build
        spack build-env openturbine -- bash
        cmake ../
        make -j 2
        ./iea15mw_turbine
