name: OpenTurbine-CI

on: push

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 2
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
    steps:
    - name: Cache install Trilinos
      id: cache-trilinos
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/spack
        key: macos-spack
    - name: Install Trilinos
      if: steps.cache-trilinos.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/spack/spack.git
        source spack/share/spack/setup-env.sh
        spack compiler find
        spack external find
        spack install googletest
        spack install trilinos@master~mpi~epetra+basker
    - name: Clone
      uses: actions/checkout@v4
      with:
        submodules: true
        path: openturbine
    - name: Test OpenTurbine
      run: |
        source spack/share/spack/setup-env.sh
        spack load trilinos
        spack load googletest
        cd openturbine
        mkdir build
        cd build
        cmake .. \
          -DOTURB_ENABLE_TESTS:BOOL=ON \
          -DOTURB_ENABLE_BASIC_SANITIZERS=ON \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} 
        cmake --build .
        ctest --output-on-failure
